#A compose file for integration tests and development
batch:
  image: camptocamp/georchestra_atlas:latest
  ports:
  - 8180:8080
  environment:
    CATALINA_OPTS: -Daws.profile=travis-build -Dmapfish.print.nb_poll_wait_status=300 -Dexport.nb_redeliveries=5
  links:
  - print
  - database

print:
  image: camptocamp/atlas_print:latest
  ports:
  - 8181:8080

database:
  image: georchestra/database
  environment:
    - POSTGRES_PASSWORD=georchestra
    - POSTGRES_USER=georchestra
    - POSTGRES_DB=georchestra
  ports:
  - 54322:5432
